### ISSUE TITLE
Improve current tab visibility

### ISSUE THREAD

**Issue by caiohofbauer** [harveycabaguio/firefox-elementary-theme#10]
This is the best Firefox theme for elementary I tried so far.
But I find it a bit difficult to quickly visualize the current tab when I have a lot of tabs opnened. Maybe you can make the unselected tabs dividers more subtle?

**Comment by harveycabaguio** [comment]
The tab dividers should be the same opacity as the elementary gtk theme now, if you still have problems, feel free to reopen/file a new issue.

**Comment by caiohofbauer** [comment]
![image](https://user-images.githubusercontent.com/19857780/41829968-480d3680-7814-11e8-81a4-502cce68883e.png)

But it's not the same.
I uploaded this screenshot so you can see the difference. In epiphany and Files, the dividers are visible ONLY on the curent tab. Non-selected tabs doesn't have dividers at all. In that way, the current tab is more visible.
I don't have a big problem finding the current tab, but you can bet some people will, especially those with eye conditions.

**Comment by caiohofbauer** [comment]
It's not just a visibility issue. It's also the feeling of focus you have, when the current tab is visually more pronounced.

**Comment by harveycabaguio** [comment]
![screenshot from 2018-06-25 18 53 32 2x](https://user-images.githubusercontent.com/2775325/41881443-3b74934c-78a9-11e8-9807-8f23df1a6397.png)
Strange, I have dividers running the default theme. I'm running the latest version of the GTK theme but I'm pretty sure its the same as in Loki.
