### ISSUE TITLE
How did you hide the title bar?

### ISSUE THREAD

**Issue by rythmkraze** [harveycabaguio/firefox-elementary-theme#20]
The screenshot in the readme shows the firefox window without the title bar. How do I remove the title bar?

**Comment by alizehctl** [comment]
@rythmkraze go in the customize panel in Firefox settings and uncheck "title bar" 

![image](https://user-images.githubusercontent.com/31581044/43389656-d6212ed8-941e-11e8-832e-6f334ee21cf9.png)

**Comment by waldyrious** [comment]
I suppose it would make sense to mention this in the README, right?

**Comment by rythmkraze** [comment]
Thanks @aadilayub :) 
All the google searches that I did not so far, none mentioned this :(

**Comment by rythmkraze** [comment]
Great job by the way :1st_place_medal:
